### PR TITLE
BC7 textures for Windows / Initial compressed texture support

### PR DESCRIPTION
**Pull request by madrazo**
Hopefully PVRTC2, ETC2(KTX) and others for mobile can follow.

This commit should not affect current behavior but it may require a
fallback for detecting non-supported hardware, or prevent texture modification.

You can use Texconv
https://github.com/Microsoft/DirectXTex/releases/tag/oct2016
( https://github.com/Microsoft/DirectXTex/tree/master/Texconv )
to convert your png to dds.
"texconv.exe" -pmalpha  -f BC7_UNORM -o out_dir in.png -m 1

Can be later tweaked to support DXT4(BC3) textures (useful for "non-cartoony"
textures) as well. It could add mipmap support as well.

You can test it with DisplayingABitmap sample.
We appreciate your comments.

### CODE REVIEW

**Comment by madrazo** [comment]
I should do 2 separate mallocs in SurfaceIO. One for the DDS headers and one for the data, so only the data is sent to SimpleSurface

**Comment by madrazo** [comment]
Now the DDS texture header is processed in OGLTexture. This makes it easier to support more DDS formats without modifying the current code. I have modified the SimpleSurface constructor to input a "data" parameter but would be better to add a different Surface type? Thanks

**Comment by madrazo** [comment]
It also crashes if I use "delete" in the CPU data
https://github.com/haxenme/nme/pull/417/files#diff-7d05115c02f5f6b21040987b75abe209R92

Using "free" instead for now.

**Comment by hughsando** [comment]
I actually have a bunch of edits going on the 'pixelformats' branch which
relate directly to the areas of code you are changing, so it is unlikely
this will get merged in its current form.
That said, it is good to see these changes at this exact stage so I can see
some of the issues to do with supporting various compressed texture
formats.  I will probably end up pasting most of the code into the final
solution one way or another.
I am also interested in workflow.  I was thinking of having some kind of
"destination format" in the nmml file so the tool can transform the source
file if it has changed (also thinking about ogg/mp3 as well), maybe even
making 2 versions (compressed, uncompressed), which will increase the
installer size, but decrease the RAM footprint if the target supports the
compressed format.  Or maybe converting to these formats at texture-load
time.

**Comment by hughsando** [comment]
"SimpleSurface" is probably a bad name now.  It is more like
"SoftwareSurface" or "SurfaceData", but I think everything can go in there
if it shares the implementation.

**Comment by madrazo** [comment]
Great news 😄 

In the case of BC7, I would really like to prepare it only offline as it takes a lot of time and our goal is to also speed up the loading time. An integrated tool with the XML would be nice (only re-convert format if the input, say PNG, has been modified). They are intended it to be "read-only", so a non-compressed version is not needed in this case. 

I still see problems showing on some textures. Sometimes they are not shown completely. So I am checking if there is a problem with the DDS or if there is a size restriction for my card.

Also, I was trying to avoid adding extra .h files but these ones could be used.  
https://github.com/Microsoft/DirectXTex/blob/master/DirectXTex/DDS.h
https://raw.githubusercontent.com/apitrace/dxsdk/master/Include/dxgiformat.h

Thanks!

**Comment by madrazo** [comment]
It seems that texconv or my GPU has an issue converting 4096x4096 textures to BC7

Also, I see that there is a -bcquick flag that would be very useful for development

**Comment by thomasuster** [comment]
Looks like this is stale. Closing for now.

**Pull request closed without merging**
