### PR TITLE
Added 'nme remake' to rebuild NME from anywhere

### PR DESCRIPTION
**Pull request by thomasuster**

### CODE REVIEW

**Comment by hughsando** [comment]
I have some similar code in tools/run/RunMain.hx, but it uses some logic to detect if nme.n is not built.
Maybe we could add a "rebuild" command here, so:
(haxelib run) nme rebuild arg1 arg2 ...
Would do pretty much the same as this script - and work on windows too.

**Comment by thomasuster** [comment]
Having problems
1) How do I invoke RunMain.hx?
2) How do I rebuild RunMain.hx?

**Comment by hughsando** [comment]
Hi,
The RunMain lives in tools/run, and you compile with "haxe compile.hxml"
This is the one ".n" file that is committed into the repo - it is designed
to be concise and to not change very often (unlike nme.n) and its main job
it to boot nme.n when developers checks out a fresh repo.
It is also a good place to do the rebuild, because you can overwrite nme.n
and the ndll files since run.n does not depend on these.

Since it builds the "run.n" script, you run it with "haxelib run nme" or
via alias "nme".  Normally it would transfer control to nme.n, but you can
do whatever you like in there.  One thing to note that, that because it is
a "haxelib run" script, the last arg passed on the command line will be
funky - it is the working directory of where the script was called from -
so you may need to "pop" this.

**Comment by thomasuster** [comment]
New commit in, how does that look?

**Comment by thomasuster** [comment]
bump

**Pull request merged**
