### PR TITLE
URLLoder based on custom Http.hx

### PR DESCRIPTION
**Pull request by codeservice**

### CODE REVIEW

**Comment by thomasuster** [comment]
Hey @codeservice , I lost the context of this. Why are you writing URLLoader based on custom Http.hx?

**Comment by codeservice** [comment]
We need to remove curl. It has issues, when I tried compile on arm64 and big in size. URLLoader based on curl doesn’t work on android and iOS now. Require latest version for this, which is tricky to integrate with NME. Custom http, easiest solution.

**Comment by thomasuster** [comment]
Oh I see, can we just have `src/nme/net/URLLoader.hx` use  `https://api.haxe.org/haxe/Http.html` instead of rolling our own?

**Comment by codeservice** [comment]
Original haxe http has no any progress notification events, only final ondata method. URLLoader require progress tracking event. Also “cancel” method missing.

**Comment by thomasuster** [comment]
Hey @simn, what are your thoughts? Could Http support progress and cancel in the future?

**Comment by Simn** [comment]
I'm not sure. Http is a bit of a mess at the moment and I'm not sure if adding more stuff to it would make that any better. I tried cleaning it up a while ago but looking at it again I don't think that worked out too well either.

**Comment by thomasuster** [comment]
@Simn Fair enough, thanks for the info.

@codeservice Alrighty, that means rolling our own seems like a reasonable approach to me. What are your thoughts on maintainability?

Here are some ideas that come to mind...
* New nme sample with progress bar
* Some unit tests `tests/haxe` for nme specific logic (progress, cancel) using MockSocket
* Perhaps it would good to pull our the URLLoader / progress / cancel stuff into a separate class that `src/nme/net/Http.hx` calls to. It would be good to make "our" diffs relative to haxe.Http clear so that if HTTP.hx updates we can just re-add our custom logic onto the newer one.

**Comment by codeservice** [comment]
>>What are your thoughts on maintainability?

I think best approach would be make new sample. I have code for this, but created in Lua, for nme library. When I have time I can translate it to haxe version.

Considering custom http. I already submitted it to nme/net folder so no interference with original haxe version. Ideally I want see haxe version similar to what I proposed.

**Comment by thomasuster** [comment]
Hey @codeservice, talked with @hughsando a bit. He's going to chat with some haxe core people on potentially exposing stub methods and then will notify this thread when he hears back.

**Comment by codeservice** [comment]
Sound great!

**Comment by thomasuster** [comment]
@hughsando Any word from haxe community Hugh?

**Comment by hughsando** [comment]
Yes - looks like it these functions could be added to the cpp(sys) versions in the standard library - which would help keep maintenance down.

**Comment by thomasuster** [comment]
@codeservice I think this is available now. https://api.haxe.org/haxe/Http.html

**Comment by codeservice** [comment]
Looks like same old http, only moved to different folder:
https://github.com/HaxeFoundation/haxe/blob/development/std/sys/Http.hx

If curl works fine, maybe we don't need custom http. I am prefer use
custom, without curl.

**Comment by thomasuster** [comment]
@codeservice But documentation says HTTP is "Available on all platforms" and I also see an if ( CPP ) conditional in there. What am I missing?

**Comment by codeservice** [comment]
NME URLLoader using curl. My proposal to use Haxe http class. Less
dependencies and smaller app size, which important for mobile. Default HTTP
class doesn’t support url loading progress event, and I had to add this to
custom HTTP class version. Idea was to add these changes to default HTTP or
use custom version.

P.S. we can close this proposal if curl good enough for NME

**Comment by codeservice** [comment]
To old PR, for haxe 4 require different approach. I am closing it.

**Pull request closed without merging**
