### PR TITLE
NME_GLES3

### PR DESCRIPTION
**Pull request by madrazo**
Initial GLES3

 All C++ changes are within a "#define NME_GLES3" and Haxe's within #if gles3
 They are not activated so it doesn't modify current behaivor and should be safe to pull. 

To use it, build nme/project with -DNME_GLES3 flag or uncomment on
ToolkitBuild.xml
Then use -Dgles3 flag when compiling a haxe NME sample.  

Tested on Windows (Angle) with https://github.com/madrazo/nme-opengl-tutorials
tutorials 1 to 5, with both -Dgles3 and without (current gles2).  

Needs small patch for SDL nme-toolkit: https://github.com/native-toolkit/sdl/pull/11/files
(it is still safe but will get a GLES2 context without this change)

Thanks

### CODE REVIEW

**Comment by madrazo** [comment]
Tested on Andoid OK.

**Comment by madrazo** [comment]
GLES2 shaders where not working with `NME_GLES3` activated because I wrote `strcmp` instead of `!strcmp`...  now is fixed and I'm also applying it to GLES2 shaders because `precision` can not be before `#version` anyway

**Comment by hughsando** [comment]
Is it possible to make this a runtime selection?  ie, use gles3 if it is there, otherwise fall back to gles2 without a define?  Maybe specify your desired level in the nmml file?

**Comment by madrazo** [comment]
Alright! Actually with NME_GLES3, it should fall back to gles2 if gles3 is not supported but the nmml flag to force gles2 is missing.

**Comment by thomasuster** [comment]
@hughsando @madrazo Who's waiting on who here?

**Comment by madrazo** [comment]
I think there is now OpenGL3 compatibility so I will check manually if something is missing. I'm checking with https://github.com/madrazo/nme-opengl-tutorials which has both GLES2 and GLES3 GLView shaders.  Closing for now.

**Pull request closed without merging**
