### PR TITLE
[winrt] Fix bin directory for newer Windows 10 SDKs

### PR DESCRIPTION
**Pull request by madrazo**
Get the newer SDK from directory name.

### CODE REVIEW

**Comment by madrazo** [comment]
@thomasuster you are right, all Windows SDKs have been 10.0... until now but that may change.  There are environment variables that could be used but I'm not sure how to retreive them. It should be using WindowsSdkVerBinPath

```
ProgramFiles(x86)=C:\Program Files (x86)
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.17763.0
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.17763.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\
WindowsSDKVersion=10.0.17763.0\
```

**Comment by thomasuster** [comment]
@madrazo Does `Sys.getEnv("WindowsSdkDir")` work?

**Comment by madrazo** [comment]
> @madrazo Does `Sys.getEnv("WindowsSdkDir")` work?

I see that if I run it from a "Developer Command Prompt for VS 2017" Sys.getEnv gets them correctly, but not from a common cmd.

I'm thinking to get the values directly from the registry as an alternative:
```
$ REG QUERY "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0" /v InstallationFolder

HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0
    InstallationFolder    REG_SZ    C:\Program Files (x86)\Windows Kits\10\


$ REG QUERY "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0" /v ProductVersion

HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0
    ProductVersion    REG_SZ    10.0.17763
```

**Comment by madrazo** [comment]
(reference)
```
        Log.verbose("run: query register");
        //REG QUERY "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0" 
        var process = new sys.io.Process('REG', ["QUERY", 'HKEY_LOCAL_MACHINE\\Software\\Wow6432Node\\Microsoft\\Microsoft SDKs\\Windows\\v10.0']);
        if (process.exitCode() != 0) {
            var message = process.stderr.readAll().toString();
            Log.error("Cannot query register. " + message);
        }
        else
        {
            var message = process.stdout.readAll().toString();
            var installationFolder = "";
            var productVersion = "";
            var lines:Array<String> = message.split("\n");
            for (line in lines)
            {
                var keyValues:Array<String> = line.split("REG_SZ");
                if(keyValues.length == 2)
                {
                   var key = StringTools.trim(keyValues[0]);
                   if(key=="InstallationFolder")
                   {
                        installationFolder = StringTools.trim(keyValues[1]);
                        Log.verbose("InstallationFolder:"+installationFolder);
                   }
                   else if(key=="ProductVersion")
                   {
                        productVersion = StringTools.trim(keyValues[1]);
                        Log.verbose("ProductVersion:"+productVersion);
                   }
                }
            }
            if(installationFolder.length>0 && productVersion.length>0)
            {
              var windowsSdkVerBinPath = installationFolder + "bin\\" + productVersion +"\\";
              Log.verbose("WindowsSdkVerBinPath:"+windowsSdkVerBinPath);
            }
        }
        process.close();
```

**Comment by madrazo** [comment]
@thomasuster It should be much better now.  Added an `initializePathVariables` function and fixed alignment

**Pull request merged**
