### PR TITLE
Initial fix for android etChar part 3

### PR DESCRIPTION
**Pull request by codeservice**

### CODE REVIEW

**Comment by hughsando** [comment]
I'm thinking it might be worth sending over all the args of onTextChanged in a single call, and handling them in NME directly.  I have just looked at a 'paste' option built into the TextField.  Currently this does not send any events, but it probably should, and it is a very similar API (add a bunch of chars, starting at given position)
The individual key-down/key up events are pretty meaningless in this case.
Sending individual 'char' events is not too bad - maybe the developer wants to cancel one, but maybe the real event is a whole string, "etString", rather than a set smaller events.
Key down/up is used for gaming, but I think we have some freedom when dealing with "virtual keys" and maybe we should just choose the API we like best.  For me, this is probably an 'etString'.  We just have to get the cpp TextField to deal with it.
What do you think?

**Comment by codeservice** [comment]
Sdl2 using key up, key down, and input events for keyboard. "Input" sound like etString. I agree it could be better to use single call onTextChange, only not sure about voice input. On android for example voice input generating many times sentences, trying to get best recognition result. Hard to predict when string is final and ready for onTextChange event. I am sending backspaces to clear previous string when new recognition result is ready, until its final. Make only one onTextChange for voice input will be tricky.

**Comment by hughsando** [comment]
I think many changes are ok.  The API might be,
onChanged( originalStringIndex0:Int, originalStringIndex1:Int,
replacement:String)
so we get a range of chars to replace (no need to backspace) or if
originalStringIndex0==originalStringIndex1 it is an insert operation.
This could also represent a deletion, without actually needing a key event,
where the replacement is the empty string.

**Comment by codeservice** [comment]
OnChanged will be fine. This method can even coexists with etchar for now and slowly replaced it over time to make less pressure.

**Comment by hughsando** [comment]
I have started on the input upgrade.
Now, it is possible to get multiple characters in the text field of TextEvent.TEXT_INPUT (currently, only by pasting text).
I think the logic should be the key up/down events are only sent for actual key events. ie, for a game that uses [space] for jump, or DPad on android.  Otherwise, all the text from input fields (particularly android and ios) generate a TEXT_INPUT events.
I think we should try to get the selectionIndexBegin and selectionIndexEnd correct before sending the TEXT_INPUT event too, which allows the application and text field to know which characters will be replaced by the input text.
This should not break anything, since the codes generate strings at the moment too, but ideally we can move towards a better separations between physical keys and actual text.

**Comment by codeservice** [comment]
What about global OnKey for stage->window. Can we keep it? This was helpful
for making simple text editors which not based on TextField object. Can we
have some kind of API for global level?

**Comment by hughsando** [comment]
I have left it in there and it should still sort-of work.  Currently, the
only thing that is generating text-based TEXT_INPUT events is when you
paste in a text field.  So if you do not have one of these, nothing should
have changed.
But I think it is important to separate key events from text events.  ie,
you should not need to fake key-down-up events.  And also for efficiency
reasons if nothing else, to expect multiple characters in the text .  In
the dictation case, where some text is replaced, maybe we need something
that says what previous text is to be replaced - the the text field can
then replace some parts if it likes.
In the SDL case, we should probably handle the paste as an OS event, so
instead of CRTL + V keys, you get a TEXT_INPUT of the data.  Instead of
using a callback, I think you can add an event listener to the stage, and
we can make sure the event goes to the stage of no text field is active.
This should still allow you to build your own text editor, but with added
features such as native paste.

**Comment by hughsando** [comment]
So I have added these changes - but I will revisit text input vs raw keys on android soon I think.

**Comment by codeservice** [comment]
Thanks!

**Pull request merged**
