### PR TITLE
Set mDirtyFlags for childrens where missing

### PR DESCRIPTION
**Pull request by codeservice**

### CODE REVIEW

**Comment by thomasuster** [comment]
Hey there, not able to compile...

```
cd samples/DisplayingABitmap
pushd ~/nme/project; neko build.n; popd; nme test mac
```

Getting...

```
Error: ./src/common/Display.cpp:1709:30: error: out-of-line definition of 'ChildrenDirty' does not match any declaration in 'nme::DisplayObjectContainer'
void DisplayObjectContainer::ChildrenDirty()
                             ^~~~~~~~~~~~~
```

**Comment by codeservice** [comment]
Fixed. Blind copy/paste very “powerful” :(

**Comment by thomasuster** [comment]
PR for https://github.com/haxenme/nme/issues/486

**Comment by thomasuster** [comment]
Tested on android, works fine.

What's this line do?
`mChildren[i]->SetBitmapCache(0);`

**Comment by codeservice** [comment]
setBitmapCache(0) delete any previously created cached bitmap. We need
this, because we set dirty flag and we going to need new cache bitmap after
rendering,

**Comment by thomasuster** [comment]
Thanks for the explanation, LGTM.

**Pull request merged**
