### PR TITLE
Clean paste from "\r\n"

### PR DESCRIPTION
**Pull request by codeservice**

### CODE REVIEW

**Comment by hughsando** [comment]
Not sure how the character codes work out, but I think the replacement needs to be done on the WideChar string to avoid possible utf8 encoding issues.

**Comment by codeservice** [comment]
I did it on utf8 level because Event declared with utf8 chars:
   const char  *utf8Text;
   int         utf8Length;
and I need to pass clean text to ontext event. Not sure how can I do this
with WideChar because its not used by events:

      Event onText(etChar);
      onText.utf8Text = utf8.c_str();
      onText.utf8Length = utf8.size();

I can convert text to WideChar first, clean it and then convert back to
utf8. Would it be fine?

**Comment by codeservice** [comment]
Also did some testing on flash. Flash cleaning "\r\n" when user get
clipboard date, not when user paste it in text. It should be done
in ExternalInterface level, not in TextField. What do you think?


var cont:ContextMenu;

    function PasteTest()
    {
        cont = new ContextMenu ();
        cont.hideBuiltInItems ();
        cont.clipboardMenu = true;

        var timer:Timer = new Timer ( 100 );

        this.contextMenu = cont;
        stage.focus = stage;

        timer.start ();

        timer.addEventListener ( TimerEvent.TIMER, onTimer );
        stage.addEventListener ( FocusEvent.FOCUS_OUT, onFocusOut );
        stage.addEventListener (Event.PASTE, onPaste );
    }

    function onTimer ( e:TimerEvent ):void
    {
        cont.clipboardItems.paste =
Clipboard.generalClipboard.formats.length;
    }

    function onPaste ( e:Event ):void
    {
        trace (
Clipboard.generalClipboard.getData(ClipboardFormats.TEXT_FORMAT) );
    }

    function onFocusOut ( e:FocusEvent ):void
    {
        stage.focus = stage;
    }
Clipboard.generalClipboard.setData(ClipboardFormats.TEXT_FORMAT, "a\r\nb")
PasteTest();

**Comment by hughsando** [comment]
Yes - good thinking.
I have added the code to strip the slash-r characters in the
GetClipboardText routine.
I

**Comment by codeservice** [comment]
Thanks!

Text field still not accepting all types of platforms for clipboard. Do we
need this changes: https://github.com/haxenme/nme/pull/295 ? or it would be
something else?

**Comment by hughsando** [comment]
Seem to have missed that one.  Should be good now.

**Pull request closed without merging**
