### PR TITLE
SoftKeyboard types 7

### PR DESCRIPTION
**Pull request by codeservice**
I will make translation from string to int values at InteractiveObject.hx getter setter level. Is this ok? In this case we have code similar to flash and no need to compare strings in cpp code. Also I can update SoftKeyboardType.hx file with inline int and remove flash support line. Could you comment this? I am not sure what recommended patterns for haxe-flash like combinations.

### CODE REVIEW

**Comment by hughsando** [comment]
Yes, there is a bit of a thing with flash using strings, where haxe enums would be better.
I think the best solution is to use "@:fakeEnum(String) extern enum SoftKeyboard" on flash, and plain enum on other targets.  This allows easy access to the index via the Type.enumIndex, so the c++ code only ever uses "int", but the haxe code accepts an Enum and converts it to an int before passing it over cffi.  In the c++ code, you can define a c++ enum with matching field positions to make it easy to understand.
If the developer types "SoftKeybaord.EMAIL" it will work on flash and native, and tracing this variable will print a nice string.
What is missing is that if the developer gets a string from, say, a file and passes this to the function.  This will work on flash, but not then on c++.  But this is a small price to pay I think.

**Comment by codeservice** [comment]
Thank you for clarifying it! Wondering if any performance benefits using
inline int vs enum. Enum has this extra call: Type.enumIndex. So for
graphics for example we have many methods with enum parameters and in case
of complex graphic data it will be many enumIndex calls.

**Comment by hughsando** [comment]
I just did some checking (and tweaking), and the enum->int should be a simple structure lookup, so very close to full speed.  Coming back the other way (ie, via a get) may not be so fast, but this is more unusual.

**Comment by codeservice** [comment]
I see new inline instance for enumIndex in hxcpp. Cool!
This will work in haxe 3.3, still have problems running nme on this version.
For example in templates ApplicationMain neko crash on ::foreach ndlls::
::if (registerPrim!=null):: extern \"C\" int ::registerPrim::();   Can't
find __s
All tools recompiled with new haxe

**Comment by hughsando** [comment]
I've basically do all my work using the new version of haxe, so I'm
interested in how neko is not working.
Are you using a new neko too?  I was on 2.0, but I just upgraded to 2.1 an
no issue.
You are you installing/using the new version of haxe?
I'm just trying "nme neko" in sample/00-Nmml

**Comment by codeservice** [comment]
Yes I am using new Neko. I downloaded it from Neko web site and it didn't work. Next attempt I installed haxe from web site with new Neko and it didn't work too, the same problem.  For experiment I removed :: foreach from template and it crash with the same message on next asset template ::foreach, I removed it too and it was crash again on something else. I did all testing on Windows. Not sure why it different to sample 00 you tested.

**Comment by codeservice** [comment]
One more interesting moment. Neko 2.1 with old Haxe works. So issue in combination new Neko and new haxe.

**Comment by hughsando** [comment]
Hey - sorry I lost this one a bit.  Where does the soft input stuff stand?
Can you do flattened PR with all the changes?

**Comment by codeservice** [comment]
I am using it already in my local NME version. Works well. I need to look
at it again and try to merge, could be problem as I now have many custom
modifications. I dont think in official NME version we did many changes in
android code and my proposal commit will land nicely here.

**Pull request closed without merging**
