### PR TITLE
Sdl2: Adjust joystick buttons for DualShock (PS3/PS4) and XBoxOne controllers

### PR DESCRIPTION
**Pull request by madrazo**
Remap some buttons when using these controllers to work properly (tested on Windows). You can revert by commenting the defines.  We also force joystick reconnection (line 1585).

### CODE REVIEW

**Comment by madrazo** [comment]
In the code there is a comment: "if SDL_JOYDEVICEREMOVED is triggered, up is fired on all buttons, so we need to counter the effect".
In this commit I have commented out this behavior since the "device added" and "device remove" were not working when unplugging and reconnecting the joysticks. We did not find an issue with the "up is fired on all buttons" so I wonder if it is still needed?  Maybe it is OK to completely remove it? Thanks

**Comment by hughsando** [comment]
HI - I have not actually used these controllers, and I was wondering why a compile-time check of the define is made.
Is it that sdl would normally assign these types to these controllers, but there is some circumstance where this might not be the case?
I'm tempted to just merge this, but would like to understand a bit more about these compile-time defines.

**Comment by madrazo** [comment]
The code comparison is not clear because I realigned the code but actually I did not remove lines, only added the ones between the defines (Commenting the defines leaves as previous) except for the line I commented out. The joystick type is retrieved on runtime by SDL_JoystickName. It seems that SDL2 manages both DirectInput and XInput joysticks but this code adjust them to behave more similar. I think in Legacy, the joystick type was just indicated in x parameter and the user has to deal with it in Haxe but our approach is to be consistent from C++. However we downgrade the functionality from for example the Triggers (R2 and L2 buttons) of the XboxOne Controller to behave as down/up buttons instead of having a sensitivity value

**Comment by madrazo** [comment]
Sorry, I have see now that the correct way to do the button mapping would be using the SDL_GameControllerAddMapping function ( https://wiki.libsdl.org/SDL_GameControllerAddMapping ). The behavoir of these controllers have already been modified in SDL (https://github.com/spurious/SDL-mirror/commits/a1fec97f67ba5b5f4a318d73adab4732f0d1cc8a/src/joystick/SDL_gamecontrollerdb.h) and may have an issue when updating the toolkit's version in future releases.

**Comment by madrazo** [comment]
However, it would need to change to the GameController API instead of the the Joystick API. Otherwise SDL_GameControllerAddMapping has no effect.

**Comment by madrazo** [comment]
I did a quick try with GameController but it seems that it is not compatible with the (older) directinput controllers, and also, I am not receiving the events when using -toolkit. So for now, I think that this is the only way to remap this buttons without losing compatibility.

**Comment by madrazo** [comment]
Closed in favor of https://github.com/haxenme/nme/pull/378. Needs testing.

**Pull request closed without merging**
