### PR TITLE
Get GL Stats

### PR DESCRIPTION
**Pull request by madrazo**
Gets an int Array of GL statistics: vertex drawn and number of calls (0 Verts, 1 Calls, 2 Element Verts, 3 Element Calls).  See extension nme-stats for a sample: https://github.com/madrazo/nme-stats

### CODE REVIEW

**Comment by thomasuster** [comment]
```
pushd nme
git checkout -b madrazo-displaystats master
git pull https://github.com/madrazo/nme.git displaystats
neko build.n
popd

git clone git@github.com:madrazo/nme-stats.git
haxelib dev nme-stats nme-stats
cd nme-stats/samples/DisplayingABitmap
nme test mac
```

screen shot 2018-11-05 at 7 34 41 pm

**Comment by madrazo** [comment]
Yes. It is just that the tabulator character `\t` is not working. You can use SPACE bar to toggle verbose and the ESC key to toggle visibility, but touch controlls should be added for mobile.

**Comment by thomasuster** [comment]
@madrazo and I talked, he's going to explore the following.

- [ ] struct for all stats instead of multiple ints
- [ ] memcopy instead of manual assign of each element in the array
- [ ] using compilation flags to not run stat code for final releases

**Comment by madrazo** [comment]
@thomasuster Added struct glStatsStruct and NME_NO_GL_STATS flag (NME compile time). Tested in Windows and Android. Tahnks

**Pull request merged**
