### PR TITLE
add JNI.createStaticField method

### PR DESCRIPTION
**Pull request by Beeblerox**
Hello!
Our team is working on porting our project from old OpenFl legacy fork to NME (since it can generate 64-bit apk files). And some of our native extensions are using JNI.createStaticField() method, which is missing in Haxe part of NME (but cpp part of NME has it). So i thought it would be nice to add it back to NME again

### CODE REVIEW

**Comment by thomasuster** [comment]
@madrazo Would you review this pull request?

**Comment by hughsando** [comment]
I think this is good in principle, but I would prefer to convert the new calls to PRIME, rather than the old class to PRIM.  The conversion should be pretty straight forward, give me a ping if you need help.

**Comment by Beeblerox** [comment]
@hughsando can you name any (sample) class in NME that uses PRIME, so i could use it as a reference?

**Comment by hughsando** [comment]
It appears your diff is changing "DEFINE_PRIME2(...)" to "DEFINE_PRIM(...,2)".
The prime version is preferred.
To go with this, you need to change the haxe code to "PrimeLoader.load" instead of "nme.Loader.load", again this diff shows an example.  The second arg to the "load" function defines the arg/return type.  In this case, everything is an object so it is "oooo" - one 'o' per arg, plus one at the end for the return type.

**Comment by Beeblerox** [comment]
@hughsando thanks for explanations! i'll make these changes tomorrow

**Comment by Beeblerox** [comment]
@hughsando i think i've fixed it

**Comment by hughsando** [comment]
I should probably have mentioned the the 'bool' fields could be treated differently, but this is good for now.

**Pull request merged**
