### PR TITLE
Fix "Failed to make complete framebuffer object" crash on iOS 13

### PR DESCRIPTION
**Pull request by Beeblerox**
Almost every time, when i lock my application on the iPhone with installed iOS 13 i get this crash "Failed to make complete framebuffer object" when i unlock device. And this tread on Apple forum has advice on how to fix it: https://forums.developer.apple.com/thread/23864
I've implemented it and it helped me to fix this crash. I've also checked if it doesn't break anything on older iOS versions and it doens't

### CODE REVIEW

**Comment by thomasuster** [comment]
@Beeblerox Looks fine to me, would you create an issue for this specific issue / stack trace / any relevant info, and then modify this PR description to say "Fixes #1234" where 1234 is the issue id. That way if the issue comes back up or needs adjustments we can have good tracking.

**Comment by Beeblerox** [comment]
@thomasuster i'll try :)

**Comment by codeservice** [comment]
Trying to replicate issue. For some reason can't break app. Checking on iOS 13.2. App compiled on xcode 11.2 Provided link has instruction, started with: Launch the app in split view. NME doesnt support split view. It's possible only run apps based on ui split view on top of NME app as popup window. I lock app, tried rotation, left in background for few minutes but in all cases app come back a live. What steps I need to do for checking?

**Comment by Beeblerox** [comment]
@codeservice i'm not sure now, Maybe my issue was due to combination of various native extensions used in our project (which we also had to change, because we have switched from OpenFL-legacy)
Maybe there is no issue, so you might close this PR.
Unfortunately i had no time or opportunity to replicate it myself since i've been reassigned to another project which doesn't involve iOS development and i don't have access to iOS devices now. Sorry

**Comment by codeservice** [comment]
Can’t close it, I am not project maintainer. Anyway, thank you for issue
reporting. In case if I see similar error I can try your approach.

**Pull request closed without merging**
