### PR TITLE
ios framebuffer fix

### PR DESCRIPTION
**Pull request by delahee**
Mandatoryif you want to be able to have proper framebuffer support on ios since apple does not respect the opengl standard.

bisous !

### CODE REVIEW

**Comment by jgranick** [comment]
This might have trouble if the framebuffer is recreated, I think it occurs on resize or possibly some other events

**Comment by delahee** [comment]
@jgranick You might be right but current impl strictly forbids proper FBO so can i suggest you merge then improve ?

**Comment by jgranick** [comment]
I fixed it like this:

https://github.com/openfl/openfl/commit/6785c7d095ee716665b88df18017ebe37ec7c78f
https://github.com/openfl/lime/commit/9302b124e2beb73893069b44288b87b708673dfa
https://github.com/openfl/openfl/commit/d8618f9259009d511be91d9dd3b91adb7c7ca261
https://github.com/openfl/lime/commit/e6e4bbf2f32954a9e051ee10c1c7752639b9351e
https://github.com/openfl/openfl/commit/6de0bdc0a25ae087343c830e3bdb8b0ec3d4f36a

**Comment by delahee** [comment]
getParameter returning instances feels strange but you know what you do,
the rest looks fine to me :)

thx !

2015-02-05 18:29 GMT+01:00 Joshua Granick <notifications@github.com>:

> I fixed it like this:
>
> openfl/openfl@6785c7d
> <https://github.com/openfl/openfl/commit/6785c7d095ee716665b88df18017ebe37ec7c78f>
> openfl/lime@9302b12
> <https://github.com/openfl/lime/commit/9302b124e2beb73893069b44288b87b708673dfa>
> openfl/openfl@d8618f9
> <https://github.com/openfl/openfl/commit/d8618f9259009d511be91d9dd3b91adb7c7ca261>
> openfl/lime@e6e4bbf
> <https://github.com/openfl/lime/commit/e6e4bbf2f32954a9e051ee10c1c7752639b9351e>
> openfl/openfl@6de0bdc
> <https://github.com/openfl/openfl/commit/6de0bdc0a25ae087343c830e3bdb8b0ec3d4f36a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haxenme/nme/pull/187#issuecomment-73088659>.
>



-- 
David Elahee

**Comment by jgranick** [comment]
Yeah, I think in Lime it is an abstract, so it returns an int, and casts to a Framebuffer, not sure. I debated that part, perhaps it should still return an int, let me know

**Comment by delahee** [comment]
1- ensure that (==) works.
2- new() is baaddddd, everytime you allocate something in an engine, ten
baby cat die.

Since getParameter is a rare and FORBIDDEN call for engine developpers
during gameplay anyway (because too slowwww)), i'll let you decide, i think
point 1 is mandatory though.

Ciao !

2015-02-05 19:44 GMT+01:00 Joshua Granick <notifications@github.com>:

> Yeah, I think in Lime it is an abstract, so it returns an int, and casts
> to a Framebuffer, not sure. I debated that part, perhaps it should still
> return an int, let me know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haxenme/nme/pull/187#issuecomment-73101846>.
>



-- 
David Elahee

**Comment by hughsando** [comment]
This is is all looking good in NME now.

**Pull request closed without merging**
