### PR TITLE
Custom haxe Http.hx file, 1st step to remove curl

### PR DESCRIPTION
**Pull request by codeservice**
I am starting removing curl if no objections. Because its long way to go, something can be missing in my proposals. Hope this process will be tested well.

### CODE REVIEW

**Comment by hughsando** [comment]
What sort of changes did you make here?  Maybe we can get them into haxe production. I notice that http for haxe version 4 has changed structure quite a bit.  Looks like it might be easier to just change the cpp version, and leave the js version untouched.

**Comment by hughsando** [comment]
Or, maybe we can not override the haxe version and make it src/nme/net/Http.hx - and only use it on cpp/neko (sys) targets.

**Comment by codeservice** [comment]
Changes:

- keep AbstractSocket from old Http. This was used in OpenSSL
implementation for custom sockets. Probably can be removed, but it was
really convenient to have abstract sockets  for custom replacements. Sad to
see this not included in new haxe.
- keep method cancel(), I don't see it in new http. I think it was in old
version. Really helpful method.
- add onBytesData( data : haxe.io.Bytes ) in addition to onData( data :
String )
- add onResponseProgress( bytesTotal : Int, bytesLoaded : Int ): Bool

For new URLLoader I need cancel and onResponseProgress.

**Comment by codeservice** [comment]
I think it reasonable. User can use original haxe Http as expected without
any custom modifications, and for URLLoad it can be new Http which includes
all missing methods

**Pull request closed without merging**
